### ISSUE TITLE
A better font

### ISSUE THREAD

**Issue by bil-elmoussaoui** [wi1d5ky/lollypop.github.io#1]
The font look terrible, maybe using a Google font? 
I don't know if you have any idea

**Comment by wi1d5ky** [comment]
I wonder what font the Mockup use so that I could use it via Google Font.
Now I am using Raleway for the Site-title, why I use it is because that font is thin, just like the font in mockup is.

**Comment by bil-elmoussaoui** [comment]
I think we can talk to the designer ?

**Comment by wi1d5ky** [comment]
Yeah, but i need to go to bed, here is 2 a.m. Haha
I will ask him/her after my work tomorrow.
Maybe you could ask him/her first.
Just let me know if you ask!

Btw, could you take a screenshot for me? I wonder what look in your system.
(What system I am using is fedora, a Linux distribution.

**Comment by wi1d5ky** [comment]
OMG, I use iPad to browse the site, it looks broken hard....
I will take it tomorrow...
![image](https://cloud.githubusercontent.com/assets/6042803/9312669/ccf3e62c-4550-11e5-8b9d-fc190337ffbf.jpg)

**Comment by bil-elmoussaoui** [comment]
I just asked him here : https://plus.google.com/+RedaLazri/posts/jFQ1ie3Pp6d 
![screenshot from 2015-08-17 20 28 33](https://cloud.githubusercontent.com/assets/7660997/9312677/90298b2a-451e-11e5-9aed-5cbfd97a0aba.png)
![screenshot from 2015-08-17 20 28 38](https://cloud.githubusercontent.com/assets/7660997/9312681/98063c1c-451e-11e5-95a9-f90aa276b793.png)

**Comment by bil-elmoussaoui** [comment]
I was thinking of having a version for mobile phones and tablets, what do you think? But finishing the desktop one is our priority at the moment

**Comment by wi1d5ky** [comment]
Yeah, I will make it responsive later
open another issue for that thx, it will remind me to do that

If you have any new idea, Just open a new issue ;-)

**Comment by wi1d5ky** [comment]
@bil-elmoussaoui no response...

**Comment by bil-elmoussaoui** [comment]
He might be on holiday ;) We should fix other issues and change the font later

**Comment by bil-elmoussaoui** [comment]
The font is Roboto

**Comment by bil-elmoussaoui** [comment]
i was going to push a new commit and i saw that you've already done ;)

**Comment by kidwm** [comment]
BTW, his github id is @0rAX0

**Comment by wi1d5ky** [comment]
@kidwm thx!

**Comment by 0rAX0** [comment]
Nice work! I may have another look with some suggestions later. Keep it up :+1:
